fail_fast: false
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.5.6
      hooks:
          # Run the linter.
          - id: ruff
            types_or: [python, pyi, jupyter]
            args: [--fix]
            verbose: true
          # Run the formatter.
          - id: ruff-format
            types_or: [python, pyi, jupyter]
            verbose: true
    - repo: local
      hooks:
          - id: prettier
            name: prettier
            entry: npx prettier
            args: [--write, --ignore-path, .ignore]
            language: system
            types: [file]
            files: \.(js|json|md|vue|yaml|yml)$ # html
            verbose: true

          - id: "markdownlint-cli2"
            name: "markdownlint-cli2"
            entry: npx markdownlint-cli2
            language: system
            types: [markdown]
            verbose: true

          - id: shfmt
            name: shfmt
            entry: shfmt
            args: [-l, -w]
            language: system
            types: [shell]
            verbose: true

          - id: shellcheck
            name: shellcheck
            entry: shellcheck
            language: system
            types: [shell]
            verbose: true
